name: Update README with Private Stats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch README stats with private repos
        env:
          LANGUAGESTATS: ${{ secrets.LANGUAGESTATS }}
        run: |
          curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=Gurmit147&layout=compact&langs_count=10&theme=radical&count_private=true&token=$LANGUAGESTATS"
          echo "![Top Langs](./top-langs.svg)" > README.md

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add README.md
            git commit -m "Update README with private stats"
            git push
          fi
