jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration
      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Authenticate with LANGUAGESTATS secret
      - name: Authenticate with LANGUAGESTATS token
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git config --global credential.helper store
          echo "https://$LANGUAGESTATS:x-oauth-basic@github.com" > ~/.git-credentials

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update README with private stats"
          git push
        env:
          LANGUAGESTATS: ${{ secrets.LANGUAGESTATS }}
